apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-user
  labels:
    app: jupyter-user
spec:
  selector:
    matchLabels:
      app: jupyter-user
  replicas: 3
  template:
    metadata:
      labels:
        app: jupyter-user
    spec:
      containers:
      - name: jupyter-user
        image: namuk2004/kbri-jupyterlab
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
