apiVersion: v1
kind: Service
metadata:
  name: service-jupyter-user
spec:
  sessionAffinity: ClientIP
  selector:
    app: jupyter-user
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
  type: NodePort
