apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ceph-user6
  labels:
    app: jupyter-ceph-user6
spec:
  selector:
    matchLabels:
      app: jupyter-ceph-user6
  replicas: 3
  template:
    metadata:
      labels:
        app: jupyter-ceph-user6
    spec:
      containers:
      - name: jupyter-ceph-user6
        image: namuk2004/kbri-jupyterlab
        #imagePullPolicy: Never
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: service-jupyter-ceph-user6
spec:
  sessionAffinity: ClientIP
  selector:
    app: jupyter-ceph-user6
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
  type: NodePort


